version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "${FASTAPI_HOST_PORT:-8001}:8000"
    env_file:
      - .env
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_HOST_PORT:-27018}:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: